### ISSUE TITLE
[solved] Error: Glib conflict

### ISSUE THREAD

**Issue by Kink03** [CodeWithKyrian/whisper.php#1]
Hi, I got a fatal error:
PHP Fatal error:  Uncaught FFI\Exception: Failed loading '/whisperphp/vendor/codewithkyrian/whisper.php/lib/linux-x86_64/libwhisper.so' (/usr/lib64/libm.so.6: version GLIBC_2.29' not found (required by /whisperphp/vendor/codewithkyrian/whisper.php/lib/linux-x86_64/libwhisper.so)) in /whisperphp/vendor/codewithkyrian/whisper.php/src/LibraryLoader.php:70

Can you build libwhisper.so with an older glib, please?
(I can't update glib on my host)

**Comment by CodeWithKyrian** [comment]
What's the version of glib on your host?

**Comment by Kink03** [comment]
Hello, it's GNU libc 2.28

**Comment by CodeWithKyrian** [comment]
Alright. I’ve updated the binaries, so you should be able to resolve it by reinstalling the package. Try it out and let me know if you encounter any further problems.

**Comment by Kink03** [comment]
Great, it works perfectly. You roxx :)
